server:
  port: 8083
  servlet:
    context-path: /api/v1

spring: 
  datasource:
    url: jdbc:mysql://195.250.31.8/zpastapana_live?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zpastapanalive
    password: zpastapana@Fixed2023
  
  jpa:
    hibernate: 
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
  profiles: default
      
  application: 
    name: zpastapana

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      
        

springdoc:
  swagger-ui:
    path: /swagger-ui-custom.html
    operations-sorter: method 