package com.zpasthapana.pojo;

import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class EmployeeResponse extends BaseRequest{
	private Long employeeId;
	private Long employeeBasicDetailsId;
	private String loginEmail;
	private String contactNumber;
	private String alternateContactNumber;
	private String pancardNumber;
	private String aadhaarCardNumber;
	private Date dateOfBirth;
	private Long religionID;
	private Integer gender;
	private Long employeeWorklocationId;
	private Date retirementDate;
	private String txtSalaryServiceIDNumber;
	private String permanentAddress;
	private String currentAddress;
	private String declaredScale;
	
	private String firstName;
	private String middleName;
	private String lastName;
	private String firstNameEng;
	private String middleNameEng;
	private String lastNameEng;
	
	private String caste;
	private String castecategory;
	private Integer casteCertificateFlag;
	private Long appointmentCasteCategoryID;
	private String casteCertificateNumber;
	private Date casteCertificateDate;
	private String casteCertificatedIssuedOfficerName;
	private String casteCertificatePDF;
	private Integer casteValidityFlag;
	private String casteValidityNumber;
	private Date casteValidityDate;
	private String casteValidityPDF;
	private String casteValidityCommitteeName;
	private Integer casteCategoryChangedAfterAppointmentFlag;
	private Integer casteCategoryChangedAfterAppointmentID;
	private String casteCategoryChangedAfterAppointmentNumber;
	private Date casteCategoryChangedAfterAppointmentDate;
	private String casteValidityChangedAfterAppointmentPDF;
	
	private String employeeselectioncategory;
	private String payCommission;
	private Integer appointmentQualificationFlag;
	private Long qualification;
	private Long parallelReservationType;
	private String salaryRange;
	private Date dateOfAppointed;
	private String appointedDateFirstPagePDF;
	private String appointmentOrderPDF;
	private Date dateOfHumanitySeniority;
	private String appointmentOrderNumber;
	private Date appointmentOrderDate;
	private String serviceBookFirstPagePDF;
	
	private Integer disabilityFlag;
	private Integer disabilityReservation;
	private String appointmentDisability;
	private Integer disabilityID;
	private String disabilityPercentage;
	private Date certificateDisabilityDate;
	private String disabilityCertificatePDF;
	
	private String universityName; 
	private String degreeName ;
	private String passoutDate  ;
	private String certificatePDF; 
	private Integer changedAfterAppointmentFlag;
	private Integer transferTypeFlag;
	private Integer furtherServiceFlag;
	private Integer medicalCertificateFlag;
	private Integer characterVerifiedFlag;
	
	private Date joiningData;
	private String appointmentQualificationExamName;
	private Date dateOfPass;
	private String appointmentQualificationPDF;
	private String characterVerifiedOrderNumber;
	private Date characterVerifiedOrderDate;
	private String characterVerifiedPDF;
	private String medicalCertificateOrderNumber;
	private Date medicalCertificateOrderDate;
	private String medicalCertificatePDF;
	private String furtherServiceOrderNumber;
	private Date furtherServiceOrderDate;
	private String furtherServicePDF;
	
	private String typingFlag;
	private String marathiHindiFlag;
	private String marathiTypingSpeed;
	private String marathiTypingSpeedPassoutDate;
	private String marathiTypingSpeedDiscountDate;
	private String marathiTypingSpeedDiscountOrderDate;
	private String marathiTypingSpeedPDF;
	private String rbtnEnglishTypingFlag;
	private String englishTypingSpeed;
	private String englishTypingSpeedPassoutDate;
	private String englishTypingSpeedDiscountDate;
	private String englishTypingSpeedDiscountOrderDate;
	private String englishTypingSpeedPDF;
	
	private String type;
	private Long stateId;
	private Long divisionId;
	private Long zpId;
	private Long subDivisionId;
	private Long departmentId;
	private Long designationId;
	private Long taluka;
	private Long subDivision;
	private Long subDepartment;
	
	private Integer concessionBrainFlag;
	private Integer concessionParalysisFlag;
	private Integer concessionHandicappeFlag;
	private Integer concessionCardiacSurgeryFlag;
	private Integer concessionDialysisFlag;
	private Integer concessionCancerFlag;
	private Integer concessionSoldierFlag;
	private Integer concessionWidowFlag;
	private Integer concessionVestalFlag;
	private Integer concessionDivorceFlag;
	private Integer concession53YearCompletedFlag;
	private Integer concessionHusbandWifeAggregationFlag;
	private Integer concessionFreedomFighterFlag;
	private Integer concessionBrainCertificateNumber;
	private String concessionBrainCertificateDate;
	private String concessionBrainTransferPeriodFlag;
	private String concessionBrainValidityDate;
	private String concessionBrainPDF;
	private Integer concessionParalysisCertificateNumber;
	private String concessionParalysisCertificateDate;
	private String concessionParalysisTransferPeriodFlag;
	private String concessionParalysisValidityDate;
	private String concessionParalysisPDF;
	private Integer concessionHandicappeCertificateNumber;
	private String concessionHandicappeCertificateDate;
	private String concessionHandicappeTransferPeriodFlag;
	private String concessionHandicappeValidityDate;
	private String concessionHandicappePDF;
	private Integer concessionCardiacSurgeryCertificateNumber;
	private String concessionCardiacSurgeryCertificateDate;
	private String concessionCardiacSurgeryTransferPeriodFlag;
	private String concessionCardiacSurgeryValidityDate;
	private String concessionCardiacSurgeryPDF;
	private Integer concessionDialysisCertificateNumber;
	private String concessionDialysisCertificateDate;
	private String concessionDialysisTransferPeriodFlag;
	private String concessionDialysisValidityDate;
	private String concessionDialysisPDF;
	private Integer concessionCancerCertificateNumber;
	private String concessionCancerCertificateDate;
	private String concessionCancerTransferPeriodFlag;
	private String concessionCancerValidityDate;
	private String concessionCancerPDF;
	private Integer concessionSoldierCertificateNumber;
	private String concessionSoldierCertificateDate;
	private String concessionSoldierTransferPeriodFlag;
	private String concessionSoldierValidityDate;
	private String concessionSoldierPDF;
	private Integer concessionWidowCertificateNumber;
	private String concessionWidowCertificateDate;
	private String concessionWidowTransferPeriodFlag;
	private String concessionWidowValidityDate;
	private String concessionWidowPDF;
	private Integer concessionVestalCertificateNumber;
	private String concessionVestalCertificateDate;
	private String concessionVestalTransferPeriodFlag;
	private String concessionVestalValidityDate;
	private String concessionVestalPDF;
	private Integer concessionDivorceCertificateNumber;
	private String concessionDivorceCertificateDate;
	private String concessionDivorceTransferPeriodFlag;
	private String concessionDivorceValidityDate;
	private String concessionDivorcePDF;
	private String concession53YearCompletedSetFlag;
	private String concessionHusbandWifeAggregationAppointmentLevelID;
	private String concessionHusbandWifeAggregationWorkingDate;
	private String concessionHusbandWifeAggregationPDF;
	private String concessionFreedomFighterName;
	private String concessionFreedomFighterRelation;
	private String concessionFreedomFighterIsLiveFlag;
	private String concessionFreedomFighterPDF;
}
